services:
  db:
    image: mysql:8.0
    container_name: sweepshare-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: sweepshare
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - sweepshare-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 30s

  api:
    build: .
    container_name: sweepshare-api-container
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      DATABASE_URL: jdbc:mysql://db:3306/sweepshare?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&useSSL=false&autoReconnect=true
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      JWT_KEY: ${JWT_KEY}
      BREVO_API_KEY: ${BREVO_API_KEY}
    networks:
      - sweepshare-network

volumes:
  mysql_data:

networks:
  sweepshare-network:
    driver: bridge
