spring.application.name=SweepShare

server.port=8080

spring.datasource.url=jdbc:mysql://localhost:3306/sweepshare?createDatabaseIfNotExist=true
spring.datasource.username=${DATABASE_USERNAME}
spring.datasource.password=${DATABASE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

api.security.token.key=${JWT_KEY}

brevo.api.key=${BREVO_API_KEY}
brevo.api.url=https://api.brevo.com/v3/smtp/email

